# Generated by Django 4.1.2 on 2022-10-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaljournal',
            options={},
        ),
    ]
