# Generated by Django 4.1.2 on 2022-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0003_alter_personaljournal_journalcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaljournal',
            name='Created',
            field=models.DateTimeField(),
        ),
    ]
