# Generated by Django 4.1.2 on 2022-10-21 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0004_alter_personaljournal_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaljournal',
            name='Modified',
        ),
        migrations.AlterField(
            model_name='personaljournal',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
