# Generated by Django 4.1.2 on 2022-10-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0006_remove_personaljournal_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaljournal',
            name='JournalImage',
            field=models.ImageField(default='static/PersonalJournal/Nature.svg', upload_to='static/'),
        ),
    ]
