# Generated by Django 4.1.2 on 2022-10-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0007_alter_personaljournal_journalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaljournal',
            name='JournalImage',
            field=models.ImageField(default='static/Nature.svg', upload_to='static/'),
        ),
    ]
