# Generated by Django 4.1.2 on 2022-10-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalJournal', '0010_personaljournal_journaldailyfruits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaljournal',
            name='JournalImage',
        ),
    ]
